--31 Determine whether a given integer number is prime. 
--32 Determine the greatest common divisor of two positive integer numbers. Use Euclid's algorithm. 
--33 Determine whether two positive integer numbers are coprime. Two numbers are coprime if their greatest common 
--   divisor equals 1. 
--34 Calculate Euler's totient function phi(m). 
--35 Determine the prime factors of a given positive integer. Construct a flat list containing the prime factors
--   in ascending order. 
--36 Determine the prime factors of a given positive integer. Construct a list containing the prime factors and 
--   their multiplicity. 
--37 Calculate Euler's totient function phi(m) (improved). Let ((p1 m1) (p2 m2) (p3 m3) ...) be the list of prime 
--   factors (and their multiplicities) of a given number m. phi(m) = (p1 - 1) * p1 ** (m1 - 1) * (p2 - 1) * p2 ** (m2 - 1) * 
--   (p3 - 1) * p3 ** (m3 - 1) * ...
--38 Compare the two methods of calculating Euler's totient function. Use the solutions of problems 34 and 37 
--   to compare the algorithms. Take the number of reductions as a measure for efficiency. Try to calculate phi(10090)
--   as an example. 
--39  A list of prime numbers. Given a range of integers by its lower and upper limit, construct a list of all
--    prime numbers in that range. 
--41 Goldbach's conjecture. Write a predicate to find the two prime numbers that sum up to a given even integer. 
